### ISSUE TITLE
Design Feedback

### ISSUE THREAD

**Issue by eugene-eeo** [eugene-eeo/tinyrecord#1]
@msiemens take a look at [line 52](https://github.com/eugene-eeo/tinyrecord/blob/master/tinyrecord/transaction.py#L52). Do you think that this is the way to go as far as ensuring that only one thread modifies a single database/table at once?

**Comment by msiemens** [comment]
Looks fine. I'd just suggest to add a small note why WeakKeyDictionary is used so people don't have to look it up on the Python docs when reading the source code.
