### ISSUE TITLE
Not compatible with tinydb 4

### ISSUE THREAD

**Issue by hugovk** [eugene-eeo/tinyrecord#11]
tinydb v4.0.0 was released this week and has a number of breaking changes:

https://tinydb.readthedocs.io/en/latest/changelog.html#v4-0-0-2020-05-02

We're using tinydb and tinyrecord like this:

```python
import os

from appdirs import user_data_dir
from tinydb import TinyDB, Query, where
from tinyrecord import transaction

DB_FILE = os.path.join(user_data_dir('pypinfo', ''), 'db.json')


def get_credentials():
    table = TinyDB(DB_FILE, create_dirs=True).table('credentials')
    query = table.search(Query().path.exists())

    return query[0]['path'] if query else None


def set_credentials(creds_file):
    table = TinyDB(DB_FILE, create_dirs=True).table('credentials')
    exists = get_credentials()

    with transaction(table) as tr:
        if exists:
            tr.update({'path': creds_file}, where('path').exists())
        else:
            tr.insert({'path': creds_file})
```

And calling `set_credentials` results in `AttributeError: 'Table' object has no attribute '_read'` (re: https://github.com/ofek/pypinfo/issues/88):

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/pypinfo", line 8, in <module>
    sys.exit(pypinfo())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pypinfo/cli.py", line 119, in pypinfo
    set_credentials(auth)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pypinfo/db.py", line 25, in set_credentials
    tr.insert({'path': creds_file})
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tinyrecord/transaction.py", line 86, in __exit__
    self.record.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tinyrecord/changeset.py", line 21, in execute
    data = self.db._read()
AttributeError: 'Table' object has no attribute '_read'
```

Also, here's some failing tinyrecord tests when building `master`:

* https://travis-ci.com/github/hugovk/tinyrecord/builds/163955326

Which pass when pinning `install: pip install "tinydb<4"` on Travis CI (https://github.com/hugovk/tinyrecord/commit/a28229f527a5d33fbf4d7c70640c3f0cdb25a3a1):

* https://travis-ci.com/github/hugovk/tinyrecord/builds/163955759

**Comment by eugene-eeo** [comment]
Hey, I'm a bit busy with exams at the moment.

If you could submit a PR that would be great, but in the meantime I am too occupied to deal with this issue. Hope you understand!

**Comment by hugovk** [comment]
Yes, I understand! No rush, we can pin to `tinydb<4` for now. Good luck with your exams!

**Comment by davidbegin** [comment]
I am using TinyDB and TinyRecord for a project, and wanted to upgrade TinyDB to 4.x.x, so I took @hugovk's branch and made the changes I needed to get the tests passing and my project working: https://github.com/hugovk/tinyrecord/compare/rm-eol...davidbegin:update-for-tinydb-4

Open to any feedback or suggestions to help move this forward and get tinyrecord updated!

**Comment by hugovk** [comment]
@davidbegin Thank you!

I made a PR of your branch into mine to trigger the CI, and there are some failures. Please could you check? 

https://github.com/hugovk/tinyrecord/pull/1
https://travis-ci.com/github/hugovk/tinyrecord/builds/174272276

**Comment by eugene-eeo** [comment]
Hey, sorry for the delay! I'm working on it now, should get a fix by the end of today. :)

**Comment by eugene-eeo** [comment]
@hugovk can you see if the master branch is working? if it is I will release, there are some minor API changes though.

**Comment by eugene-eeo** [comment]
@hugovk I wrote this library when I was 15 so there was a massive oversight on my part :sweat_smile:
the following does what tinyrecord does (and more, in particular letting you query the data you wrote),
and maintains API-compatibility with TinyDB:

```python
from tinydb import TinyDB
from tinydb.table import Table
from tinydb.storages import MemoryStorage
import contextlib


class AbortTransaction(Exception):
    pass


def abort():
    raise AbortTransaction


@contextlib.contextmanager
def transaction(table: Table):
    data = table.storage.read()
    if data is None:
        data = {}

    data = {table.document_id_class(id): doc for id, doc in data.items()}
    db = TinyDB(storage=MemoryStorage)

    tmp_table = db.table(table.name)
    tmp_table.storage.write(data)

    try:
        yield tmp_table

        table.storage.write(data)
        table._next_id = None

    except AbortTransaction:
        pass
```

Maybe I should replace tinyrecord's code with this :)

**Comment by hugovk** [comment]
I've done a CI build with tinydb 4 and tinyrecord `master` (https://github.com/hugovk/pypinfo/commit/35b91db01f3eed73ea040f4d4323b994faa390a5) and it fails like this:

```
    def test_get_credentials_table(tmp_path):
        db.DB_FILE = str(tmp_path / 'db.json')
        with db.get_credentials_table() as table:
>           assert not table._storage._storage._handle.closed
E           AttributeError: 'JSONStorage' object has no attribute '_storage'
```

Here's the files that use tinydb/tinyrecord:

* https://github.com/ofek/pypinfo/blob/8296094c0d110611679106c9ea83430f8e201c4b/pypinfo/db.py
* https://github.com/ofek/pypinfo/blob/8296094c0d110611679106c9ea83430f8e201c4b/tests/test_db.py

What changes are needed there? Thanks!

**Comment by eugene-eeo** [comment]
Maybe it's because of the repeated `_storage`? Maybe change this line:

    assert not table._storage._storage._handle.closed

to:

    assert not table._storage._handle.closed

**Comment by hugovk** [comment]
That's now passing, thanks!

* https://github.com/hugovk/pypinfo/commit/6321422f22777876050066bb7d6de603d43076aa
* https://travis-ci.org/github/hugovk/pypinfo/jobs/705133853

**Comment by eugene-eeo** [comment]
Cool, I'll make a release now and you can pin it to the upcoming release :)

**Comment by hugovk** [comment]
Great, thank you very much!
