### ISSUE TITLE
ACID?

### ISSUE THREAD

**Issue by alexreg** [eugene-eeo/tinyrecord#13]
Does this provide atomicity as in ACID, or just in the weaker sense?

**Comment by eugene-eeo** [comment]
Hi, if there is only one process using the TinyDB database, and also if you use the transaction locks properly, then yeah I would say it's sort of ACID -- transactions are atomic, isolation is kind of supported..., consistency is up in the air (there are no schemas, but if a transaction commits then you've moved to a consistent state - where consistent is up to you), durability is dependent on how you store your data (what storage you use).

Hope it answers your question

**Comment by alexreg** [comment]
Thanks for clarifying!
