### ISSUE TITLE
How to get eid of the record after an insert

### ISSUE THREAD

**Issue by abnerjacobsen** [eugene-eeo/tinyrecord#2]
Hi,

I'm using tinyrecord but stuck in an problem. How I can get the eid of a newly create record ?

I'm using this code:

```
       with database.transaction(table) as tr:
            newid = tr.insert(record.to_struct())

```

But the newid variable is always eq None.

Any idea on how solve this ?

Regards,

**Comment by eugene-eeo** [comment]
There is no way to get the EID currently, sorry! Do you want to write a PR for that?

**Comment by eugene-eeo** [comment]
With that being said you shouldn't rely on it, especially outside of the transaction should the transaction fail, because the IDs will be invalid.
