### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by msiemens** [eugene-eeo/tinyrecord#3]
There've been a few changes to the transaction locks that fix bugs with multiple threads that haven't been released to PyPI (mainly 5a3cbeaeb0efd31b325604b3924421a4e1fddf9e). Could we get a new version released?

For reference, a bug with multiple threads and tinyrecords has been reported here: https://forum.m-siemens.de/d/11-json-gets-corrupted-no-idea-how-to-trace-it

**Comment by eugene-eeo** [comment]
👍 done. The latest version is [0.1.3](https://pypi.python.org/pypi/tinyrecord/0.1.3).

**Comment by msiemens** [comment]
Thanks for the quick response as usual :heart:
