### ISSUE TITLE
Corrupted Json file when writing with multiple threads

### ISSUE THREAD

**Issue by MrLeeh** [eugene-eeo/tinyrecord#4]
I just was trying a small example to test if *tinyrecords* provides a safe way of reading and writing data to a tinydb file from multiple threads. Unluckily I always end up with corrupted database files. So maybe I got it wrong and tinyrecords isn't for multithreading? I know about tinydb not being suitable for multithreading but assumed tinyrecords is a plugin adding multithreading capability. Or maybe I'm just handling it the wrong way?

Here is my simple test code:

```python
import threading

from tinydb import TinyDB, where
from tinyrecord import transaction

db = TinyDB('db.json')
table = db.table('settings')
table.purge()
db.close()


def increment_values():

    db = TinyDB('db.json')
    table = db.table('settings')
    table.insert({'name': 'test', 'value': 0})

    for i in range(100):
        with transaction(table) as tr:
            item = table.search(where('name') == 'test')[0]
            item['value'] += 1
            tr.remove(where('name') == 'test')
            tr.insert(item)


t1 = threading.Thread(target=increment_values)
t2 = threading.Thread(target=increment_values)

t1.start()
t2.start()

t1.join()
t2.join()
```

**Comment by eugene-eeo** [comment]
It's been a while since I worked on the code, give me some time to get back to you. :)

**Comment by MrLeeh** [comment]
Ah, I see. I modified the code according to your suggestions and now it works just fine. With the `update_callable` function it even gains some extra speed.

My first approach was the classic read - modify - write way. I know it is less efficient then `update_callable` but offers more flexibility. So if I want to get it working I need to place statements for reading data outside of the `with` block. 

Like so:

```python
def increment_values_slow(lock):
    for i in range(int(COUNT / THREADS)):
        lock.acquire()
        item = table.search(where('name') == 'test')[0]
        val = item['value']
        with transaction(table) as tr:
            tr.update({'value': val + 1}, where('name') == 'test')
        lock.release()
```

Would you agree on this approach or am I missing something?

**Comment by eugene-eeo** [comment]
@MrLeeh yes that is the correct way to do it, but is slightly less efficient than my example. If there is enough demand I would separate and expose the locking component if you really require per-table locks.

**Comment by MrLeeh** [comment]
Actually it would be great if one could do the querrying within the with-bock so there would be no need for a Lock object at all. Something like this maybe:

```python
def increment_values_slow(lock):
    for i in range(int(COUNT / THREADS)):
        with transaction(table) as tr:
            item = tr.table.search(where('name') == 'test')[0]
            val = item['value']
            tr.update({'value': val + 1}, where('name') == 'test')
```
But I don't know if this is possible. As I understand it you don't lock inside the with statement but only for the execution time of the update which is called when the with block is left. So this would mean to also execute the tr.table.search within the locked state.

**Comment by eugene-eeo** [comment]
I prefer the explicit Lock object so that the developer using it knows that he/she is using a lock so there are no surprises. It is technically possible to do the querying, etc. within the with block but preserving the current semantics, but it would require some serious magic that I am not prepared to maintain. I'm closing this thread but I will be open to any ideas if you reach out through email.
