### ISSUE TITLE
threaded application

### ISSUE THREAD

**Issue by joaoreis81** [eugene-eeo/tinyrecord#5]
I'm using tinydb and facing problems with threaded application. The database corrupts. 
Does tinyrecord solve the concurrency problem?
Thanks.

**Comment by eugene-eeo** [comment]
@joaoreis81 as long as you do not run multiple processes that all write to the same file at the same time, you will be fine. tinyrecord only makes sure that the DB will not be corrupted when you modify it from multiple threads in the _same process_.
