### ISSUE TITLE
transaction upsert

### ISSUE THREAD

**Issue by wiryonolau** [eugene-eeo/tinyrecord#9]
Hi, since tinyrecord transaction doesn't support upsert

Is it safe to run this inside transaction
1) search record 
2) check if record available
3) any kind of logic .. 
4) update or insert

Also is it possible to remove from mutliple table inside single tx

I'm using multiple threading to access  the database

**Comment by eugene-eeo** [comment]
Hi, if all threads use tinyrecord then it should be fine. Otherwise it is not since tinyrecord supports only thread locks (synchronized within the same process).
